// Serialize a brand_voice.guidelines JSONB into a clean Markdown document
// suitable for sharing with contractors, saving to Notion, or printing.

interface Guidelines {
  positioning_statement?: string
  mission?: string
  vision?: string
  brand_values?: string[]
  voice_traits?: Array<{
    trait: string
    description: string
    we_are?: string[]
    we_are_not?: string[]
  }>
  tone_by_context?: Record<string, string>
  messaging_matrix?: Array<{
    audience_segment: string
    pain_point: string
    promise: string
    proof: string
    cta: string
  }>
  taglines?: string[]
  elevator_pitches?: Record<string, string>
  vocabulary?: { always_use?: string[]; never_use?: string[] }
  story?: string
}

function section(title: string, body: string): string {
  return body.trim() ? `\n## ${title}\n\n${body.trim()}\n` : ''
}

function bulletList(items?: string[]): string {
  if (!items || items.length === 0) return ''
  return items.map((i) => `- ${i}`).join('\n')
}

export function guidelinesToMarkdown(
  projectName: string,
  guidelines: Guidelines,
): string {
  const out: string[] = []
  out.push(`# ${projectName} — Brand Book`)
  out.push(`\n_Generated by GrowthOS on ${new Date().toISOString().slice(0, 10)}_\n`)

  if (guidelines.positioning_statement) {
    out.push(section('Positioning', `> ${guidelines.positioning_statement}`))
  }

  const missionVision: string[] = []
  if (guidelines.mission) missionVision.push(`**Mission.** ${guidelines.mission}`)
  if (guidelines.vision) missionVision.push(`**Vision.** ${guidelines.vision}`)
  if (missionVision.length) out.push(section('Mission & Vision', missionVision.join('\n\n')))

  if (guidelines.brand_values?.length) {
    out.push(section('Brand Values', bulletList(guidelines.brand_values)))
  }

  if (guidelines.voice_traits?.length) {
    const body = guidelines.voice_traits.map((t) => {
      const we = bulletList(t.we_are)
      const not = bulletList(t.we_are_not)
      return [
        `### ${t.trait}`,
        t.description,
        we ? `**We are**\n${we}` : '',
        not ? `**We are not**\n${not}` : '',
      ].filter(Boolean).join('\n\n')
    }).join('\n\n---\n\n')
    out.push(section('Voice Traits', body))
  }

  if (guidelines.tone_by_context && Object.keys(guidelines.tone_by_context).length) {
    const body = Object.entries(guidelines.tone_by_context)
      .map(([ctx, tone]) => `- **${ctx}.** ${tone}`)
      .join('\n')
    out.push(section('Tone by Context', body))
  }

  if (guidelines.messaging_matrix?.length) {
    const header = '| Segment | Pain | Promise | Proof | CTA |'
    const sep = '| --- | --- | --- | --- | --- |'
    const rows = guidelines.messaging_matrix.map((m) =>
      `| ${[m.audience_segment, m.pain_point, m.promise, m.proof, m.cta]
        .map((v) => (v ?? '').replace(/\n/g, ' ').replace(/\|/g, '\\|')).join(' | ')} |`
    )
    out.push(section('Messaging Matrix', [header, sep, ...rows].join('\n')))
  }

  if (guidelines.taglines?.length) {
    out.push(section('Taglines', guidelines.taglines.map((t) => `- "${t}"`).join('\n')))
  }

  if (guidelines.elevator_pitches && Object.keys(guidelines.elevator_pitches).length) {
    const body = Object.entries(guidelines.elevator_pitches)
      .map(([k, v]) => `**${k.replace(/_/g, ' ')}**\n\n> ${v}`)
      .join('\n\n')
    out.push(section('Elevator Pitches', body))
  }

  const vocabBody: string[] = []
  if (guidelines.vocabulary?.always_use?.length) {
    vocabBody.push(`**Always use**\n${bulletList(guidelines.vocabulary.always_use)}`)
  }
  if (guidelines.vocabulary?.never_use?.length) {
    vocabBody.push(`**Never use**\n${bulletList(guidelines.vocabulary.never_use)}`)
  }
  if (vocabBody.length) out.push(section('Vocabulary', vocabBody.join('\n\n')))

  if (guidelines.story) {
    out.push(section('Brand Story', guidelines.story))
  }

  return out.join('\n').replace(/\n{3,}/g, '\n\n').trim() + '\n'
}
