import { describe, it, expect } from 'vitest'
import { guidelinesToMarkdown } from './brand-book-export'

describe('guidelinesToMarkdown', () => {
  it('renders a minimal brand book with just positioning', () => {
    const md = guidelinesToMarkdown('Acme', {
      positioning_statement: 'The only ops tool your team needs.',
    })
    expect(md).toContain('# Acme — Brand Book')
    expect(md).toContain('## Positioning')
    expect(md).toContain('> The only ops tool your team needs.')
  })

  it('renders voice traits with we-are / we-are-not bullets', () => {
    const md = guidelinesToMarkdown('Acme', {
      voice_traits: [
        { trait: 'Calm', description: 'Never panicked.', we_are: ['measured', 'quiet'], we_are_not: ['hypey', 'shouty'] },
      ],
    })
    expect(md).toContain('### Calm')
    expect(md).toContain('**We are**')
    expect(md).toContain('- measured')
    expect(md).toContain('**We are not**')
    expect(md).toContain('- shouty')
  })

  it('renders messaging matrix as a real markdown table and escapes pipes', () => {
    const md = guidelinesToMarkdown('Acme', {
      messaging_matrix: [
        { audience_segment: 'B2B', pain_point: 'spreadsheets', promise: 'one view', proof: '10k users', cta: 'try it | free' },
      ],
    })
    expect(md).toContain('| Segment | Pain | Promise | Proof | CTA |')
    expect(md).toContain('| --- | --- | --- | --- | --- |')
    // Escaped pipe inside CTA cell
    expect(md).toContain('try it \\| free')
  })

  it('omits sections that have no content instead of emitting empty headings', () => {
    const md = guidelinesToMarkdown('Acme', {
      positioning_statement: 'x',
    })
    expect(md).not.toContain('## Voice Traits')
    expect(md).not.toContain('## Taglines')
    expect(md).not.toContain('## Brand Story')
  })

  it('collapses runs of 3+ blank lines', () => {
    const md = guidelinesToMarkdown('Acme', {
      positioning_statement: 'a',
      story: 'b',
    })
    expect(md).not.toMatch(/\n\n\n/)
  })

  it('is deterministic and includes the generated-on date stamp (ISO YYYY-MM-DD)', () => {
    const md = guidelinesToMarkdown('Acme', { positioning_statement: 'x' })
    expect(md).toMatch(/_Generated by GrowthOS on \d{4}-\d{2}-\d{2}_/)
  })
})
